# Generated by Django 2.1.2 on 2018-10-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0002_auto_20181016_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
