# Generated by Django 2.1.2 on 2018-10-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0004_auto_20181016_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='users_images/'),
        ),
    ]
