# Generated by Django 2.1.2 on 2018-10-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0005_review_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
        migrations.AddField(
            model_name='review',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='users_images'),
        ),
    ]
