# Generated by Django 2.1.2 on 2018-10-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0007_auto_20181017_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='users_images'),
        ),
    ]
