# Generated by Django 2.1.2 on 2018-10-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0008_auto_20181017_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pic',
            field=models.ImageField(blank=True, default='users_images/image.jpg', upload_to='users_images', verbose_name='Photo'),
        ),
    ]
