# Generated by Django 2.1.2 on 2018-10-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0009_auto_20181017_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pic',
            field=models.ImageField(blank=True, upload_to='users_images', verbose_name='Photo'),
        ),
    ]
