# Generated by Django 2.1.2 on 2018-10-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0010_auto_20181017_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pic',
        ),
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, upload_to='users_images', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='review',
            name='img_min',
            field=models.ImageField(blank=True, upload_to='users_images_min', verbose_name='photo_min'),
        ),
    ]
