# Generated by Django 2.1.2 on 2018-10-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0011_auto_20181018_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date_pub']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='img_min',
        ),
    ]
