# Generated by Django 2.1.2 on 2018-10-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0012_auto_20181018_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='photo'),
        ),
    ]
