# Generated by Django 2.1.2 on 2018-10-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest_Book', '0013_auto_20181018_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['name']},
        ),
    ]
